name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    uses: arek-devops-platform/platform-workflows/.github/workflows/python-test.yml@main

  security:
    uses: arek-devops-platform/platform-workflows/.github/workflows/security-scan.yml@main